"""
Boardgame Bazaar: home App - Apps
"""


from django.apps import AppConfig


class HomeConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'home'
