"""
Boardgame Bazaar: cart App - Apps
"""


from django.apps import AppConfig


class CartConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'cart'
