# Generated by Django 3.2.6 on 2021-10-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
