"""
Boardgame Bazaar: contact App - Apps
"""


from django.apps import AppConfig


class ContactConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'contact'
