"""
Boardgame Bazaar: profiles App - Apps
"""


from django.apps import AppConfig


class ProfilesConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'profiles'
