# Generated by Django 3.2.6 on 2021-10-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
