"""
Boardgame Bazaar: checkout App - Apps
"""


from django.apps import AppConfig


class CheckoutConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'checkout'

    def ready(self):
        import checkout.signals
