"""
Boardgame Bazaar: products App - Apps
"""


from django.apps import AppConfig


class ProductsConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'products'

    def ready(self):
        import products.signals
