"""
Boardgame Bazaar: mailing_list App - Apps
"""


from django.apps import AppConfig


class MailingListConfig(AppConfig):
    """
    App configuration (generated by Django)
    """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'mailing_list'
