# Generated by Django 3.2.6 on 2021-08-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterUniqueTogether(
            name='genreassignment',
            unique_together={('genre', 'Product')},
        ),
    ]
