# Generated by Django 3.2.6 on 2021-08-24 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210822_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
