# Generated by Django 3.2.6 on 2021-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_genreassignment_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='ratings_total',
            field=models.IntegerField(default=0),
        ),
    ]
