# Generated by Django 3.2.6 on 2021-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210824_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
