# Generated by Django 3.2.6 on 2021-09-27 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20210923_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
