# Generated by Django 3.2.6 on 2021-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210824_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genreassignment',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='genreassignment',
            unique_together={('genre', 'product')},
        ),
    ]
