# Generated by Django 3.2.6 on 2021-09-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wishlist',
        ),
    ]
