# Generated by Django 3.2.6 on 2021-08-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
    ]
