# Generated by Django 3.2.6 on 2021-10-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211004_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_rating',
            new_name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratings_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ratings_total',
        ),
    ]
