# Generated by Django 3.2.6 on 2021-08-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_genre_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_seller',
        ),
    ]
