# Generated by Django 3.2.6 on 2021-10-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_avg_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avg_rating',
            new_name='rating',
        ),
    ]
