# Generated by Django 3.2.6 on 2021-10-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_avg_rating_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
